[theme]
# Primary accent color for interactive elements.
primaryColor = "#2E3092"  # Dark Blue color similar to the buttons

# Background color for the main content area.
backgroundColor = "#F6F6F6"  # Light Gray background similar to the webpage

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FFFFFF"  # White background for sidebar

# Color used for almost all text.
textColor = "#333333"  # Dark Gray text color

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"